### ISSUE TITLE
Finishing a first draft

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/underreact#1]
Making a checklist about what I know needs to be done:

- [x] Easy CSS pipeline — maybe (probably?) a separate tool: basically [Batfish](https://github.com/mapbox/batfish)'s stylesheets processor.
- [x] Config validation with [Fusspot](https://github.com/mapbox/fusspot).
- [x] Quick draft documentation, enough to facilitate beta testing.
- [x] A few more examples using a few more options.
- [x] New package name (chunk-light is taken).
- [x] Add to HTML any `<link>`s for CSS assets created by Webpack plugins the user provides.
- [x] Env variable option.
- [x] Expose Webpack version so configs can use it to add plugins.
- [x] Reject HTML with closing head and body tags, which we need so we know where to put things. 
- [x] Optionally write stats during build.

**Comment by jingsam** [comment]
What are the differences between chunk-light and chunk-light-public?

**Comment by davidtheclark** [comment]
@jingsam "chunk-light-public" is just a temporary name before initial release. chunk-light was an internal-only React starter kit with some Mapbox-specific preferences built in. We'll need to come up with a new name for this public package, before release.
