### ISSUE TITLE
Ditch fs-extra

### ISSUE THREAD

**Issue by kepta** [mapbox/underreact#15]
In light of memory leaking bug (thanks to @davidtheclark) in node-graceful-fs https://github.com/isaacs/node-graceful-fs/issues/102 which `fs-extra` depends on, we should not be using `fs-extra`. Since this project is in initial phases, it would be relatively easy to port. Also, `node 8+` have a native solution to the promisification of node API's. 
Currently we have two options 
1. Continue using `pify` since it is already being used and works well.
2. Port to using the `util.promisify`, which is a first party wrapper for node's callback API.

I am a bit inclined to no.2 because it is a standard API and would work well with existing node ecosystem. To support the node `v6` we can use the polyfill [util/promisify](https://github.com/ljharb/util.promisify). 
@davidtheclark thoughts?

**Comment by davidtheclark** [comment]
Unfortunately, we can't make this reliant on Node 8 until our internal publishing system supports Node 8.

**Comment by kepta** [comment]
It won't if we use https://github.com/ljharb/util.promisify

**Comment by kepta** [comment]
This was done in https://github.com/mapbox/underreact/pull/19
