### ISSUE TITLE
PostCSS concatenator is not hashing files

### ISSUE THREAD

**Issue by kepta** [mapbox/underreact#36]
I believe this is a bug since PostCSS concatenator [earlier](https://github.com/mapbox/underreact/blob/master/lib/packageable/postcss-concatenator.js#L20) used to accept `hash` parameter, but in the latest code hashing functionality is missing.

**Comment by davidtheclark** [comment]
This was intentional, because we decided the concatenator function itself would be cleaner if it didn't have to worry about that; instead, a separate processing step could take the file, hash it, and rename it.

You can go with whatever you think is best.

**Comment by kepta** [comment]
This is no longer valid as we are using Webpack for css loading.
