### ISSUE TITLE
Sourcemaps don't work with simply renaming css later

### ISSUE THREAD

**Issue by kepta** [mapbox/underreact#39]
(Related https://github.com/mapbox/underreact/issues/36)

With the recent implementation of hashing, the source map url in the generated css file doesn't get updated. This happens because we are providing a [different output path](https://github.com/mapbox/underreact/blob/a7b5401ffb5e37f6ec285258d08c299aaafbe39f/packages/postcss-concatenator/index.js#L66). 
As this will make any source map binded to provided path, simply calculating the hash and [writting](https://github.com/mapbox/underreact/blob/a7b5401ffb5e37f6ec285258d08c299aaafbe39f/packages/postcss-concatenator/index.js#L74) to new output would not work.

https://github.com/mapbox/underreact/blob/a7b5401ffb5e37f6ec285258d08c299aaafbe39f/packages/postcss-concatenator/index.js#L62-L83

**Comment by davidtheclark** [comment]
You could look at Batfish's implementation as an example: https://github.com/mapbox/batfish/blob/503064de33ebffa407bbdf5d20e44a8c71964ccd/src/node/compile-stylesheets.js#L165-L183

**Comment by kepta** [comment]
Oh I see! Thanks @davidtheclark, this would do the job.

**Comment by kepta** [comment]
This is no longer valid as we are using Webpack for css loading.
