### ISSUE TITLE
The default value of `DEPLOY_ENV` is confusing

### ISSUE THREAD

**Issue by kepta** [mapbox/underreact#74]
The default value for `DEPLOY_ENV` is being set to `production`. This leads to a non-intuitive behaviour of seeing a build in my local machine **dangerously** using production API. I think a fix would be either to make setting `DEPLOY_ENV` during build explicit or using `development` or `local` as a default value. I personally think `development` would cause least surprises. 

Thanks to @davidtheclark for pointing this one out.

**Comment by davidtheclark** [comment]
👍 `development` makes sense. You should be able to deliberately set it when you know you're not building for development.
