### ISSUE TITLE
Svg React transform and CSS loader

### ISSUE THREAD

**Issue by kepta** [mapbox/underreact#76]
It seems like `url(xyz.svg)` in a CSS  is triggering `svg-react-transformer-loader` to convert it into a JS code and causing problems. The output CSS looks something like this:
<img width="553" alt="image" src="https://user-images.githubusercontent.com/6966254/49069127-822a9600-f24e-11e8-9924-f0e9290e9f37.png">

I am not sure what would be the best way to prevent handling of this type of SVG import with `react-transformer-loader`. @davidtheclark any thoughts ?

**Comment by davidtheclark** [comment]
This is what css-loader does. Why do we need to use css-loader at all?

**Comment by kepta** [comment]
So that the assets are under the control of Webpack i.e. convert their url to `Underreact-assets/css/snowflake-4522.svg)`.

**Comment by kepta** [comment]
Oh looks like there is an option https://webpack.js.org/configuration/module/#rule-issuer exactly for this problem.
